version: "3"

services:

  db:
    image: postgres:14-alpine
    container_name: musubi_postgres 
    ports: 
      - "15432:5432"
    environment:
      - "POSTGRES_USER=musubi"
      - "POSTGRES_PASSWORD=Hogepiyo"
      - "POSTGRES_DB=musubi"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      musubi_net:
        ipv4_address: 172.16.0.2

  app:
    build: ./tomcat
    container_name: musubi_tomcat
    volumes:
      - "./tomcat/musubi.war:/usr/local/tomcat/webapps/musubi.war:rw"
      #- "./tomcat/logs:/usr/local/tomcat/logs:cached"
    ports:
      - "8090:8080"
      - "9000:8000"
    environment:
      TZ: Asia/Tokyo
      JPDA_ADDRESS: 0.0.0.0:8000
      JPDA_TRANSPORT: dt_socket
    networks:
      musubi_net:
        ipv4_address: 172.16.0.3

networks:
  musubi_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
