name: Test,Build,Deploy Jobs
on:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17
    steps:
      - name: start
        run: echo Test start
      - name: checkout
        uses: actions/checkout@v2  
      - run: ls
      - run: cd ./infra/src
      - run: ls
      - name: end
        run: echo Test end

  Build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17
    needs: Test
    steps:
      - name: start
        run: echo Build start
      - name: end
        run: echo Test end  