name: Test,Build,Deploy Jobs
on:
  push:

jobs:
  Build1:
    runs-on: ubuntu-latest
    steps:
      - run: echo Build1

  Build2:
    runs-on: ubuntu-latest
    needs: Build1
    steps:
      - run: echo Build2